print("I always come back!")
print("my names Gus")
print("       _=,_         ")
print("    o_/6 /#\        ")
print("    \__ |##/        ")
print("     ='|--\         ")
print("       /   #'-.     ")
print("       \#|_   _'-. /")
print("        |/ \_( # |  ")
print("       C/ ,--___/   ")
